name: LipFD
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  python==3.11.5
  pip:
  - ftfy==6.1.1
  - librosa==0.10.1
  - matplotlib==3.8.0
  - numpy==1.25.2
  - opencv-contrib-python==4.8.1.78
  - opencv-python==4.8.1.78
  - scikit-learn==1.3.1
  - torch==2.2.0+cu121
  - torchvision==0.17.0+cu121
  - tqdm==4.66.1